override-pv: false
openOnVaultClose: false
disablePurchases: false
#List of available items: https/:/hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html
allowCustomization: false

gui:
  name: "&f[&4Player Vaults Menu&f]"
  fillitem: "BLACK_STAINED_GLASS_PANE"
unlocked:
  name: "&7[&aUnlocked&7]"
  item: 'GREEN_STAINED_GLASS_PANE'
  lore:
    - "&2&m--------------------"
    - "&f[&4Vault #<VAULTNUM>&f]"
    - "&7[&aLeft-Click&7] Open Vault"
    #    - "&7[&aMiddle-Click&7] Edit Name" #Optional lore when allowCustomization is true
    #    - "&7[&aRight-Click&7] Edit Icon"
    - "&2&m--------------------"
locked:
  name: "&7[&cLocked&7]"
  item: 'RED_STAINED_GLASS_PANE'
  lore:
    - "&c&m--------------------"
    - "&f[&4Vault #<VAULTNUM>&f]"
    - "&7[&aLeft-Click&7] To Purchase"
    - "&3Cost&6: &2$&a<COST>"
    - "&c&m--------------------"
key:
  consume: false
  firstJoin: true
  name: "&f[&4Player Vaults Menu&f]"
  item: 'CHEST'
  lore:
    - "&c&m--------------------"
    - "&7Vaults For Players"
    - "&7Hold and Right Click"
    - "&7[&aRight-Click To Open&7]"
    - "&c&m--------------------"

messages:
  # SD Messages
  # 0 = command label, 1 = command args, 2 = description
  command-usage: '&7Correct Usage &a/{0} {1} &7- &b{2}'
  # 0 = thing could not find.
  not-found: '&cCould not find {0}.'
  command-error: '&cError whilst executing this command ({0}). Please report to a member of staff'
  # 0 = something, 1 = thing 0 is not.
  invalid: '&c{0} is not a valid {1}'

  # 0 = vault bought
  buySuccess: "&aYou bought &7Vault #{0}"
  noVaultAccess: "&cYou have to buy the previous Vault first!"
  vaultLocked: "&cThis vault is locked"
  consumeKey: "&aYou used a menu key"
  insufficientFunds: "&cInsufficient Funds!"

defaultcost: 10000
defaultMatrix: true
matrix:
  - '         '
  - ' xxxxxxx '
  - 'b       f'
vaults:
  1:
    cost: 250
  2:
    cost: 500
  3:
    cost: 750
  4:
    cost: 1000
  5:
    cost: 1250
  6:
    cost: 1500
  7:
    cost: 1750
