name: PlayerVaultsGUI
version: ${project.version}
main: net.poweredbyawesome.playervaultsgui.PlayerVaultsGUI
depend: [SDCore, Vault]
authors: [LaxWasHere, Ellie]
api-version: 1.15

commands:
  pvbuy:
  pvguireload: